### ISSUE TITLE
Wiki addition: LCD Display Function page

### ISSUE THREAD

**Issue by basilhussain** [TonyChatfield/S1-RX8-AC-Display-controller#2]
When looking through the list of icons, where MKRAM addresses are mapped to LCD symbols, I was curious to note that there were two symbols that have been omitted: the prime (′) and double-prime (″) marks on the right-hand side of the central character area. The former between characters 10 & 11, and the latter after character 12. Presumably they are used to designate minutes and seconds.

Experimentation revealed that they are _both_ controlled by the same bit in the register at MKRAM address 0x9B, offset 0x04. That is, toggling this bit turns them both on/off at the same time - they cannot be controlled separately.

So, the wiki page's icons table should be updated to read as follows:

Icon9B; not used, fan7, **min/sec prime marks**, R/H vertical divider, Full Stop between DDRAM #11 & #12

(Or substitute with however you feel they should be described.)

I don't actually recall whether or not the RX-8's display output ever actually uses these symbols - I would imagine if so perhaps for CD audio track time elapsed? - but they are there and can be utilised nonetheless. :)

**Comment by TonyChatfield** [comment]
Good find, it seems I did have these flagged in my initial tests but they were dropped at some point
possibly as I needed glasses and just couldn't see them again or I may have been undecided about them sharing the one register.
Makes perfect sense to have them tied together as part of a 'time' display.
