### ISSUE TITLE
Wiki correction: LCD display wiring page

### ISSUE THREAD

**Issue by basilhussain** [TonyChatfield/S1-RX8-AC-Display-controller#3]
Another correction, this time for the LCD display wiring page in the wiki.

On the pin-out listing, pin 9 (purple/black) is listed as being +5V. I have recently discovered that it is not a power circuit, but is actually an inhibit input, presumably corresponding to the inhibit pin of the NJU6623 display controller.

This input is active-low, so the audio unit will be seen outputting 5V (i.e. a high level) to keep the LCD on. If this input is grounded, it should put the LCD into a low-power standby mode, where all text and icons are turned off, but contents of DD/MK/CGRAM are preserved.

So, in the pin-out listing, pin 9 should be relabelled as 'LCD Inhibit/Standby (active low)', or similar.

**Comment by TonyChatfield** [comment]
Connection details updated
Thanks
